import type { ReasoningPipeline } from "@/services/brain/reasoningPipeline/reasoningPipelineTypes";

export function formatReasoningPipelineForPrompt(
  pipeline: ReasoningPipeline,
): string {
  const { evidence, memory, reasoning, decision } = pipeline;

  return [
    "ATHENA EVIDENCE-FIRST REASONING PIPELINE (AUTHORITATIVE — DO NOT CONTRADICT):",
    "",
    "EVIDENCE EXTRACTION (grounded facts only):",
    `- Explicit buyer need: ${evidence.explicitBuyerNeed ?? "Not stated"}`,
    `- Pain points: ${evidence.statedPainPoints.join("; ") || "None recorded"}`,
    `- Objections: ${evidence.objections.join("; ") || "None recorded"}`,
    `- Urgency signals: ${evidence.urgencySignals.join("; ") || "None recorded"}`,
    `- Buying intent: ${evidence.buyingIntent ?? "Unclear"}`,
    `- Decision criteria: ${evidence.decisionCriteria.join("; ") || "None recorded"}`,
    `- Constraints: ${evidence.constraints.join("; ") || "None recorded"}`,
    `- Requested solution: ${evidence.requestedSolution ?? "None stated"}`,
    `- Emotional tone: ${evidence.emotionalTone ?? "Neutral/unknown"}`,
    `- Evidence snippets: ${evidence.quotedEvidenceSnippets.join(" | ") || "None extracted"}`,
    `- Missing information: ${evidence.missingInformation.join("; ") || "None flagged"}`,
    `- Evidence confidence: ${evidence.confidence}`,
    "",
    "RELEVANT MEMORY (organization-scoped):",
    `- Recurring objections: ${memory.recurringObjections.join("; ") || "None"}`,
    `- Recurring buyer concerns: ${memory.recurringBuyerConcerns.join("; ") || "None"}`,
    `- Prior winning angles: ${memory.priorWinningAngles.join("; ") || "None"}`,
    `- Prior rejected angles: ${memory.priorRejectedAngles.join("; ") || "None"}`,
    `- Existing assets: ${memory.existingAssets.join("; ") || "None"}`,
    `- Existing positioning: ${memory.existingPositioning ?? "Not recorded"}`,
    `- Domain terminology: ${memory.relevantDomainTerminology.join(", ") || "None"}`,
    "",
    "BUSINESS REASONING:",
    `- Real opportunity: ${reasoning.realBusinessOpportunity}`,
    `- Why now: ${reasoning.whyItMattersNow}`,
    `- Highest-leverage move: ${reasoning.highestLeverageMove}`,
    `- Generic response to avoid: ${reasoning.genericResponseToAvoid}`,
    `- Why avoid generic: ${reasoning.whyAvoidGenericResponse}`,
    `- Senior operator action: ${reasoning.seniorOperatorAction}`,
    `- Supporting evidence: ${reasoning.supportingEvidence.join("; ") || "Limited"}`,
    `- Memory support: ${reasoning.memorySupport.join("; ") || "None"}`,
    `- Memory contradictions: ${reasoning.memoryContradictions.join("; ") || "None"}`,
    `- Risks: ${reasoning.risks.join("; ") || "None flagged"}`,
    `- Reasoning confidence: ${reasoning.confidence}`,
    "",
    "BUSINESS DECISION (single selected action — all outputs must follow this):",
    `- Decision: ${decision.decision}`,
    `- Rationale: ${decision.rationale}`,
    `- Why this beats alternatives: ${decision.whyThisBeatsAlternatives}`,
    `- Target audience: ${decision.targetAudience}`,
    `- Intended outcome: ${decision.intendedOutcome}`,
    `- Primary CTA: ${decision.primaryCta}`,
    `- Recommended channel: ${decision.recommendedChannel}`,
    `- Urgency: ${decision.urgency}`,
    `- Success metric: ${decision.successMetric}`,
    `- Why this asset: ${decision.whyThisAsset}`,
    `- Recommended asset type: ${decision.recommendedAssetType}`,
    `- Decision confidence: ${decision.confidence}`,
    "",
    "INSTRUCTIONS:",
    "Generate outputs from Evidence + Memory + Business Reasoning + Business Decision.",
    "Do not invent a different strategy. Do not contradict the Business Decision.",
  ].join("\n");
}
