export const SEO_PROSPECT_PDF_PAGE = {
  size: "A4" as const,
  width: 595.28,
  height: 841.89,
  marginLeft: 54,
  marginRight: 54,
  marginTop: 72,
  marginBottom: 56,
  contentWidth: 487,
  footerY: 28,
  headerY: 34,
  bottomGuard: 78,
  coverLeftRule: 8,
} as const;

export const SEO_PROSPECT_PDF_TYPE = {
  coverEyebrow: 8.5,
  coverTitle: 34,
  coverPrepared: 9.5,
  coverSubject: 20,
  coverMetaLabel: 8,
  coverMetaValue: 10.5,
  sectionNumber: 8,
  sectionTitle: 16,
  subsection: 11.5,
  lede: 11.75,
  body: 10.5,
  label: 8,
  metadata: 8.5,
  footer: 7.5,
  header: 7.5,
  kpiValue: 36,
  kpiDenom: 11,
  badge: 7.5,
  code: 8,
  closeEyebrow: 8.5,
  closeTitle: 22,
  closeBrand: 16,
} as const;

export const SEO_PROSPECT_PDF_SPACE = {
  afterSection: 16,
  afterBlock: 11,
  afterParagraph: 8,
  listGap: 3.2,
  cardPadX: 14,
  cardPadY: 12,
  snapshotGap: 12,
  appendixRow: 8,
  rule: 0.6,
  brandRule: 1.75,
} as const;
